# Generated by Django 2.2 on 2021-09-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FattigueInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('login_user', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('vehiclenumber', models.CharField(max_length=100)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fatigue', models.CharField(max_length=100)),
                ('c_date', models.DateField()),
            ],
            options={
                'db_table': 'FatigueInfo',
            },
        ),
    ]
