# Generated by Django 2.2 on 2021-09-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fattigueinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fattigueinfomodel',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
